name: Docker Image CI

on:
  push:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Build the Docker image
      uses: docker/build-push-action@v1
      with:
        registry: ghcr.io
        username: "CoryEvans2324"
        password: ${{ secrets.GITHUB_TOKEN }}
        repository: coryevans2324/html-to-pdf
        tags: latest
